import {
  startech_mfti,
  sber_team_cert,
  sber_cert,
  itechpred,
  iprof1,
  iprof2,
  hackathon_mfti,
  hackathon_kaspersky,
  det1,
  ustu_1st_place1,
  ustu_1st_place2,
  ustu_1st_place3,
  ty_letter,
  cod,
} from "./assets";
export const services = [
  {
    id: 1,
    img: "https://i.ibb.co/VYyv3MC/youknow.png",
    link: "https://youknow.academai.ru",
    title: "YouKnow",
  },
  {
    id: 2,
    img: "https://i.ibb.co/sRDQV5q/academai.png",
    link: "https://academai.ru",
    title: "AcademAI",
  },
  {
    id: 3,
    img: "https://i.ibb.co/6FmJSzK/amiks.png",
    link: "https://sroamiks.ru/",
    title: "Amiks",
  },
  {
    id: 4,
    img: "https://i.ibb.co/0n9JB0g/v2-0.png",
    link: "https://www.figma.com/file/w7vpdhatGsvJSzulhy6HaR/%D0%A3%D0%97%D0%A1%D0%9C?type=design&node-id=0%3A1&mode=design&t=JnZzhdf4hYSI5tOB-1",
    title: "UZSM",
  },
  {
    id: 5,
    img: "https://i.ibb.co/Ss9swGx/Capture-Page-7.png",
    link: "https://sushiboss11.ru/",
    title: "SushiBoss",
  },
  {
    id: 6,
    img: "https://i.ibb.co/1sG5Qb0/Group-1.png",
    link: "https://github.com/ArsenKakasyan/Cloud",
    title: "FileCloud",
  },
  {
    id: 7,
    img: "https://i.ibb.co/cCpYsVM/Screenshot-4.png",
    link: "https://t.me/NeurengineBot",
    title: "NeurengineBot",
  },
  {
    id: 8,
    img: "https://i.ibb.co/VqFPbK7/Screenshot-11.png",
    link: "https://github.com/AcademAI/qr_inventarization",
    title: "QRecord",
  },
  {
    id: 9,
    img: "https://i.ibb.co/GW08RqG/github.png",
    link: "https://github.com/AcademAI",
    title: "and more..",
  },
];

export const awards = [
  {
    id: 1,
    title: "Diploma for winning ",
    description: "",
    imageUrl: startech_mfti,
  },
  {
    id: 2,
    title: "SberStudent accelerator",
    description: "",
    imageUrl: sber_team_cert,
  },
  {
    id: 3,
    title: "SberStudent accelerator",
    description: "",
    imageUrl: sber_cert,
  },
  {
    id: 4,
    title: "ITechpred",
    description: "",
    imageUrl: itechpred,
  },
  {
    id: 5,
    title: "IProf",
    description: "",
    imageUrl: iprof1,
  },
  {
    id: 6,
    title: "IProf",
    description: "",
    imageUrl: iprof2,
  },
  {
    id: 7,
    title: "Hackathon MIPT",
    description: "",
    imageUrl: hackathon_mfti,
  },
  {
    id: 8,
    title: "Hackathon Kaspersky",
    description: "",
    imageUrl: hackathon_kaspersky,
  },
  {
    id: 9,
    title: "English certificate",
    description: "",
    imageUrl: det1,
  },
  {
    id: 10,
    title: "USTU 1st place",
    description: "",
    imageUrl: ustu_1st_place1,
  },
  {
    id: 11,
    title: "USTU 1st place",
    description: "",
    imageUrl: ustu_1st_place2,
  },
  {
    id: 12,
    title: "USTU 1st place",
    description: "",
    imageUrl: ustu_1st_place3,
  },
  {
    id: 13,
    title: "University gratitude letter",
    description: "",
    imageUrl: ty_letter,
  },
  {
    id: 14,
    title: "Cloud of ideas",
    description: "",
    imageUrl: cod,
  },
];
